CREATE TABLE tenants
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    secret_token VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tenants PRIMARY KEY (id),
    CONSTRAINT uk_tenants_secret_token UNIQUE (secret_token)
);

CREATE TABLE aqi_data_points
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city      VARCHAR(255)                            NOT NULL,
    aqi_value DOUBLE PRECISION                        NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_aqi_data_points PRIMARY KEY (id)
);
