ALTER TABLE sensor_nodes ADD COLUMN active BOOLEAN DEFAULT TRUE;

DROP TABLE aqi_data_points;

CREATE TABLE sensor_readings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sensor_id   VARCHAR(255),
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    temperature DOUBLE PRECISION DEFAULT 0              NOT NULL,
    humidity    DOUBLE PRECISION DEFAULT 0              NOT NULL,
    mq4_ch4     DOUBLE PRECISION DEFAULT 0,
    mq7_co      DOUBLE PRECISION DEFAULT 0,
    mq135_air   DOUBLE PRECISION DEFAULT 0,
    dust_ugm3   DOUBLE PRECISION DEFAULT 0,
    CONSTRAINT pk_sensor_readings PRIMARY KEY (id)
);

ALTER TABLE sensor_readings
    ADD CONSTRAINT FK_SENSOR_READINGS_ON_SENSOR FOREIGN KEY (sensor_id) REFERENCES sensor_nodes (id);