CREATE TABLE pollution_reports
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude    DOUBLE PRECISION                        NOT NULL,
    longitude   DOUBLE PRECISION                        NOT NULL,
    report_type VARCHAR(255)                            NOT NULL,
    description TEXT,
    reported_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_name   VARCHAR(255),
    CONSTRAINT pk_pollution_reports PRIMARY KEY (id)
);